import { test, expect } from '@playwright/test';

test('Page Accessibility Tests', async ({ page }) => {
  await page.goto('https://team-uhp.vercel.app/');
  await page.getByRole('heading', { name: 'Welcome to TeamUHp' }).click();
  await page.getByRole('button', { name: 'View Projects' }).click();
  await page.getByRole('textbox', { name: 'Enter email' }).click();
  await page.getByRole('textbox', { name: 'Enter email' }).fill('admin@hawaii.edu');
  await page.getByRole('textbox', { name: 'Enter email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('changeme');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Projects List' }).click();
  await page.getByRole('heading', { name: 'Projects List' }).click();
  await page.getByRole('link', { name: 'Add Project' }).click();
  await page.getByRole('heading', { name: 'Add Project' }).click();
  await page.locator('input[name="title"]').click();
  await page.locator('textarea[name="descrip"]').click();
  await page.getByRole('link', { name: 'Back to Project List' }).click();
  await page.getByRole('link', { name: 'No Image The FitnessGram' }).click();
  await page.getByRole('heading', { name: 'The FitnessGram Pacer Test' }).click();
  await page.getByText('The FitnessGram Pacer Test is').click();
  await page.getByRole('button', { name: 'Ad Min Ad Min' }).click();
  await page.getByRole('button', { name: 'Edit Profile' }).click();
  await page.getByRole('heading', { name: 'Edit Profile' }).click();
  await page.locator('#home-page-nav').click();
  await page.getByRole('heading', { name: 'Welcome to TeamUHp' }).click();
  await page.getByRole('link', { name: 'Projects List' }).click();
  await page.getByRole('link', { name: 'No Image Non-Admin User Test' }).click();
  await page.getByRole('button', { name: 'I\'m On a Boat' }).click();
  await page.getByRole('link', { name: 'Apply for this opening' }).click();
  await page.getByRole('heading', { name: 'Application for Non-Admin' }).click();
  await page.getByRole('link', { name: 'Back to Opening' }).click();
  await page.getByRole('heading', { name: 'I\'m On a Boat' }).click();
  await page.getByRole('link', { name: 'Back to Project' }).click();
  await page.getByRole('heading', { name: 'Non-Admin User Test In Case' }).click();
  await page.getByRole('link', { name: '< Back to List of Projects' }).click();
  await page.locator('#Footer').click();
  await page.getByRole('button', { name: 'admin@hawaii.edu' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByRole('heading', { name: 'Ad Min' }).click();
  await page.getByRole('heading', { name: 'Projects' }).click();
  await page.getByRole('button', { name: 'admin@hawaii.edu' }).click();
  await page.getByRole('link', { name: 'Change Password' }).click();
  await page.getByRole('heading', { name: 'Change Password' }).click();
  await page.getByRole('button', { name: 'admin@hawaii.edu' }).click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
  await page.getByRole('heading', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Yes, Sign Out' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Sign up' }).click();
  await page.getByRole('heading', { name: 'UH Mānoa Sign Up' }).click();
});