import { test } from '@playwright/test';

test('Page Accessibility Tests', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('heading', { name: 'Welcome to TeamUHp' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Sign in' }).click();
  await page.getByRole('heading', { name: 'UH Mānoa Sign In' }).click();
  await page.getByRole('link', { name: 'Create account' }).click();
  await page.getByRole('heading', { name: 'UH Mānoa Sign Up' }).click();
  await page.getByRole('link', { name: 'Already have an account? Sign' }).click();
  await page.getByRole('heading', { name: 'UH Mānoa Sign In' }).click();
  await page.getByRole('link', { name: 'Forgot Password?' }).click();
  await page.getByRole('heading', { name: 'Forgot Password?' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Enter email' }).click();
  await page.getByRole('textbox', { name: 'Enter email' }).fill('admin@hawaii.edu');
  await page.getByRole('textbox', { name: 'Enter email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('changeme');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('heading', { name: 'Projects List' }).click();
  await page.getByRole('link', { name: 'Add Project' }).click();
  await page.getByRole('heading', { name: 'Add Project' }).click();
  await page.locator('input[name="title"]').click();
  await page.locator('input[name="title"]').fill('CI Test Project');
  await page.getByRole('textbox', { name: 'Pick a date' }).click();
  await page.getByRole('button', { name: 'Next Month' }).click();
  await page.getByRole('gridcell', { name: 'Choose Tuesday, December 30th,' }).click();
  await page.locator('textarea[name="descrip"]').click();
  await page.locator('textarea[name="descrip"]').fill('Ci Test Project');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Projects List' }).click();
  await page.getByRole('link', { name: 'No Image CI Test Project Due' }).click();
  await page.getByRole('heading', { name: 'CI Test Project' }).click();
  await page.getByRole('button', { name: 'Ad Min Ad Min' }).click();
  await page.getByRole('heading', { name: 'Ad Min' }).click();
  await page.getByRole('link', { name: 'No Image CI Test Project Due' }).click();
  await page.getByRole('button', { name: 'Recruit for Opening' }).click();
  await page.locator('input[name="title"]').click();
  await page.locator('input[name="title"]').fill('CI Test Opening');
  await page.getByRole('textbox', { name: 'Select a start and end date' }).click();
  await page.getByRole('button', { name: 'Next Month' }).click();
  await page.getByRole('gridcell', { name: 'Choose Tuesday, December 30th,' }).click();
  await page.locator('textarea[name="descrip"]').click();
  await page.locator('textarea[name="descrip"]').fill('CI Test Opening');
  await page.getByRole('checkbox', { name: 'React' }).check();
  await page.getByRole('checkbox', { name: 'Lisp' }).check();
  await page.getByRole('checkbox', { name: 'CryEngine' }).check();
  await page.getByRole('checkbox', { name: 'programming' }).check();
  await page.getByRole('heading', { name: 'Recruit for Opening' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Looking for Skills:').click();
  await page.getByRole('button', { name: 'CI Test Opening' }).click();
  await page.getByRole('heading', { name: 'CI Test Opening' }).click();
  await page.getByText('React').click();
  await page.getByRole('link', { name: 'Apply for this opening' }).click();
  await page.getByRole('heading', { name: 'Application for CI Test' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('CI Test Application');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('heading', { name: 'Applications' }).click();
  await page.getByRole('link', { name: 'Edit Opening' }).click();
  await page.getByRole('heading', { name: 'Edit Opening' }).click();
  await page.getByRole('link', { name: 'Back to Opening' }).click();
  await page.getByRole('link', { name: 'CI Test Project' }).click();
  await page.getByText('React').click();
  await page.getByRole('button', { name: 'CI Test Opening' }).click();
  await page.getByRole('link', { name: 'Ad Min' }).click();
  await page.getByRole('heading', { name: 'Applicant:' }).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Accept' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'admin@hawaii.edu' }).click();
  await page.getByRole('link', { name: 'Profile', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Profile' }).click();
  await page.getByRole('heading', { name: 'Edit Profile' }).click();
  await page.locator('#home-page-nav').click();
  await page.getByRole('heading', { name: 'Welcome to TeamUHp' }).click();
  await page.getByRole('button', { name: 'admin@hawaii.edu' }).click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Yes, Sign Out' }).click();
  await page.getByRole('heading', { name: 'Welcome to TeamUHp' }).click();
});