export const ComponentIDs = {
  addProjectMenuItem: 'addProjectMenuItem',
  addProjectFormName: 'addProjectFormName',
  addProjectFormPicture: 'addProjectFormPicture',
  addProjectFormHomePage: 'addProjectFormHomePage',
  addProjectFormDescription: 'addProjectFormDescription',
  addProjectFormInterests: 'addProjectFormInterests',
  addProjectFormParticipants: 'addProjectFormParticipants',
  addProjectFormSubmit: 'addProjectFormSubmit',
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterFormInterests: 'filterFormInterests',
  filterFormSubmit: 'filterFormSubmit',
  filterMenuItem: 'filterMenuItem',
  homeFormFirstName: 'homeFormFirstName',
  homeFormLastName: 'homeFormLastName',
  homeFormBio: 'homeFormBio',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  interestsMenuItem: 'interestsMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  luckyMenuItem: 'luckyMenuItem',
  profilesMenuItem: 'profilesMenuItem',
  projectInfo: 'projectInfo',
  projectsMenuItem: 'projectsMenuItem',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormSubmit: 'signUpFormSubmit',
};

export const PageIDs = {
  addProjectPage: 'addProjectPage',
  filterPage: 'filterPage',
  homePage: 'homePage',
  interestsPage: 'interestsPage',
  landingPage: 'landingPage',
  luckyPage: 'luckyPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  openingPage: 'openingPage',
  profilesPage: 'profilesPage',
  projectsList: 'projectsList',
  projectPage: 'projectPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
};
