-- AlterTable
ALTER TABLE "Position" ADD COLUMN     "admins" INTEGER[],
ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "skills" SET DEFAULT ARRAY[]::"Skills"[],
ALTER COLUMN "member" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "positions" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "skills" SET DEFAULT ARRAY[]::"Skills"[];

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "availability" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "contacts" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "skills" SET DEFAULT ARRAY[]::"Skills"[];
